### PR TITLE
ShowWindow

### PR DESCRIPTION
**Pull request by huangqinjin**
image

### CODE REVIEW

**Comment by stefankueng** [comment]
I think this should be done in src/resources/windowmessages.xml

**Comment by huangqinjin** [comment]
Probably not, no window messages are equivalent to `ShowWindow`.

**Comment by stefankueng** [comment]
well, you can extend the file. And maybe extending it with 'constants' so that instead of a hex value the name of the constant is shown.

**Comment by huangqinjin** [comment]
I don't think it worth doing that currently. The number of possible values of `nCmdShow` parameter is rather small.

Extending with 'constants' can be done later if we want to support third API (currently only `SendMessage` and `ShowWindow`).

**Pull request merged**
